# Generated by Django 5.2.4 on 2025-11-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointmentnote",
            old_name="noteText",
            new_name="note_text",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="number",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="appointmentnote",
            name="noteType",
        ),
        migrations.RemoveField(
            model_name="appointmentnote",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmentnote",
            name="note_type",
            field=models.CharField(
                choices=[("D", "DOCTOR"), ("P", "PATIENT")],
                default="nothing",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "PENDING"),
                    ("C", "CONFIRMED"),
                    ("X", "CANCELLED"),
                    ("D", "COMPLETED"),
                    ("N", "NO_SHOW"),
                    ("I", "IN_PROGRESS"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentnote",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="appointment_notes",
                to="appointments.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("T", "TEST"),
                    ("I", "IMAGING"),
                    ("C", "CONSULTATION"),
                    ("O", "OTHER"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="service_orders",
                to="appointments.service",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="status",
            field=models.CharField(
                choices=[("O", "ORDERED"), ("C", "COMPLETED")], max_length=20
            ),
        ),
    ]
