# Generated by Django 5.2.4 on 2025-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_rename_notetext_appointmentnote_note_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="symptoms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
