# Generated by Django 5.2.4 on 2025-11-14 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_remove_medicine_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptiondetail",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="prescription_details",
                to="pharmacy.prescription",
            ),
        ),
    ]
